algoritmo "ListaLTP"
// Função : area do triangulo
// Autor : IHMHR
// Data : 11/02/2015
// Seção de Declarações
var
   base,altura,area:real
inicio
// Seção de Comandos
   escreval("Digite o valor da base do triângulo:")
   leia(base)
   escreval("Digite o valor da altura do triângulo:")
   leia(altura)

   area <- (base*altura) / 2

   escreval("O valor da área do triângulo é: ", area)
fimalgoritmo
