algoritmo "ListaLTP"
// Função : media 3 numeros
// Autor : IHMHR
// Data : 13/02/2015
// Seção de Declarações
var
   num1,num2,num3,media:real
inicio
// Seção de Comandos
   escreval("Digite o primeiro número:")
   leia(num1)
   escreval("Digite o segundo número:")
   leia(num2)
   escreval("Digite o terceiro número:")
   leia(num3)
   
   media <- (num1+num2+num3) / 3
   
   escreval("a média dos 3 números é: ", media)
fimalgoritmo
