algoritmo "ListaLTP"
// Função : perimetro retangulo
// Autor : IHMHR
// Data : 12/02/2015
// Seção de Declarações
var
   lado1,lado2,perimetro:real
inicio
// Seção de Comandos
   escreval("Digite o valor do primeiro lado:")
   leia(lado1)
   escreval("Digite o valor do segundo lado:")
   leia(lado2)

   perimetro <- (lado1 * 2) + (lado2 * 2)

   escreval("O valor do perimetro do retângulo é: ", perimetro)
fimalgoritmo
