algoritmo "ListaLTP"
// Função : calcular perimetro triangulo
// Autor : IHMHR
// Data : 12/02/2015
// Seção de Declarações
var
   lado1,lado2,lado3,perimetro:real
inicio
// Seção de Comandos
   escreval("Digite o valor do primeiro lado:")
   leia(lado1)
   escreval("Digite o valor do segundo lado:")
   leia(lado2)
   escreval("Digite o valor do terceilo lado:")
   leia(lado3)

   perimetro <- lado1 + lado2 + lado3

   escreval("O valor da perimêtro do triângulo é: ", perimetro)
fimalgoritmo
