algoritmo "Exercicio 1"
// Função : posição dos elementos do vetor
// Autor : IHMHR
// Data : 28/04/2015
// Seção de Declarações
var
A: vetor[1..10] de inteiro
i:inteiro
inicio
// Seção de Comandos
para i de 1 ate 10 faca
   escreval("Digite um valor para a posição",i," do vetor: ")
   leia(A[i])
fimpara
para i de 1 ate 10 faca
   escreval("O vetor na posição",i," tem o valor:",A[i])
fimpara
fimalgoritmo
